### PR TITLE
Move circleci directory

### PR DESCRIPTION
**Pull request by marians**
In that PR https://github.com/giantswarm/fmt/pull/92 I placed the new file wrong. This should fix it.

### CODE REVIEW

**Comment by kopiczko** [comment]
I didn't notice that. Let's please rename to all-circleci-best-practices.md and update the link in the main readme to keep things consistent.

**Comment by marians** [comment]
Done

**Comment by kopiczko** [comment]
... and update the link in the main readme ...

**Comment by marians** [comment]
Done

**Review by rossf7 — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]

**Review by oponder — APPROVED** [review]
LGTM!

**Pull request merged**
