### PR TITLE
Add example for errors from outside packages

### PR DESCRIPTION
**Pull request by MarcelMue**
Just adding an example how we can align outside errors with our error pattern. 
It doesn't seem to fit very nicely into the flow of this file right now, feedback welcome.

Any suggestions for a better example or is this okay?

### CODE REVIEW

**Comment by MarcelMue** [comment]
No clue why there were whitespaces, but now they're gone.

**Review by tuommaki — APPROVED** [review]
LGTM :+1:

**Review by kopiczko — APPROVED** [review]

**Review by rossf7 — APPROVED** [review]
Nice, LGTM.

**Comment by MarcelMue** [comment]
Got 3 approvals, going with this.

**Pull request merged**
