### PR TITLE
go: add idempotency conventions

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Review by xh3b4sd — APPROVED** [review]
That makes sense to me and is very clear.

**Review by rossf7 — APPROVED** [review]
Nice. Thanks for adding.

**Review by MarcelMue — APPROVED** [review]
:+1:

**Review by TheoBrigitte — APPROVED** [review]
Love it!

**Comment by indyfree** [comment]
good writeup, thanks!

**Pull request merged**
