### PR TITLE
Add section about nancy to Go guide

### PR DESCRIPTION
**Pull request by stone-z**
Nancy is a vulnerability scanner for Go dependencies. It will be added to `architect-orb` by https://github.com/giantswarm/architect-orb/pull/173

This section includes some info about what to expect and how to work with it

### CODE REVIEW

**Comment by stone-z** [comment]
Pinging @giantswarm/chapter-pe as this will eventually apply to all Go code

**Comment by xh3b4sd** [comment]
The advice is to ignore vulnerabilities. IMO when we do that we don't need the integration at all. At which point should we escalate and maybe look for a better alternative of the vulnerable dependency? When would we say we try to fix it ourselves? How do we want to measure impact?

**Comment by stone-z** [comment]
> The advice is to ignore vulnerabilities.

Of course not, the advice is to 1. update the dependency, 2.override it using `replace` if you can't update it directly, and then 3. ignore if it cannot be updated. I will add some text to highlight that.

**Comment by xh3b4sd** [comment]
I understand. Though, looking down the road, the consequence will be that we start to ignore reports. How to deal with that?

**Review by corest — APPROVED** [review]

**Comment by stone-z** [comment]
I'd like to proceed with this, @xh3b4sd please let me know if you think there should be something else included here

**Pull request merged**
